Rasa process starting
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/weathernlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Sending message: Hello!
Sending message: In which location?
Encountered an exception while running action 'action_get_weather'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/weathernlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Sending message: How may I help you today?
Failed to run custom action 'action_get_weather'. Action server responded with a non 200 status code of 404. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 404 Client Error: NOT FOUND for url: http://localhost:5055/webhook/
Encountered an exception while running action 'action_get_weather'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
